OWNERS, README.md
This PR adds preliminary OWNERS and README.md files.
=> Add readme and owners

.ci-operator.yaml
Needed for https://github.com/openshift/release/pull/19919
=> Add .ci-operator.yaml with base_root_image

OWNERS
=> OWNERS: add arjunrn

Makefile, README.md, docs/localdev.md
This PR refers to the JIRA subtask : https://issues.redhat.com/browse/CFE-162
Verified on CRC version `crc-linux-1.33.1-amd64 `
=> Add README for CRC local development

api/v1alpha1/externaldns_webhook.go, api/v1alpha1/webhook_test.go
This change adds validation for ExternalDNS resource for the hostname annotation policy. If the policy is `Ignore` then an `fqdnTemplate` has to be specified. Also the provider credentials should be configured correctly.
=> Credentials and hostname annotation validation for resource

api/v1alpha1/externaldns_types.go, config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml, config/samples/aws/operator_v1alpha1_externaldns_complex.yaml, docs/usage.md
The idea is to clarify some less intuitive parts about the matching of the source against the destination zones.
=> Add more complex CR example

README.md
This commit fixes the documentation for OLM when a developer tries to deploy his operator image via OLM.
=>  This commit fixes the documentation for OLM when a developer tries to deploy his operator image via OLM

api/v1alpha1/externaldns_types.go, config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml, pkg/operator/controller/externaldns/deployment.go, pkg/operator/controller/externaldns/deployment_test.go, pkg/operator/controller/externaldns/pod.go, pkg/operator/controller/externaldns/test/vars.go
This PR addresses the selection of  the private zone provider when the user creates an ExternalDNS CR in Azure for private zone deployment
=> Bug 2027281: Update to ensure private zone provider is selected for Azure Cloud

config/samples/gcp/kustomization.yaml, config/samples/gcp/operator_v1alpha1_externaldns_openshift.yaml
A sample CR for external dns operator with source route.
=> A sample CR for external dns operator with source route in OpenShift enviroment on GCP..

config/samples/azure/kustomization.yaml, config/samples/azure/operator_v1alpha1_externaldns_openshift.yaml
Sample CR for external dns operator to work on Azure in Openshift.
=> Sample CR for external dns operator to work on Azure in Openshift.

config/samples/aws/kustomization.yaml, config/samples/aws/operator_v1alpha1_externaldns_openshift.yaml
CR for using external dns on OpenShift in AWS environment.
=> CR for using external dns on OpenShift in AWS environment.

docs/gcp-openshift.md
Documentation for external operator on OpenShift in GCP environment.
=> Documentation for external operator on OpenShift in GCP environment.

docs/azure-openshift.md
Document for using Azure external dns with OpenShift.
=> Document for using Azure external dns with OpenShift.

Dockerfile
Leverage UBI to build and run the container image.
=> Use ubi for container images

bundle/manifests/external-dns-operator_clusterserviceversion.yaml
bundle/manifests/external-dns-operator_clusterserviceversion.yaml
This is based on the information in https://docs.openshift.com/container-platform/4.9/operators/understanding/olm/olm-workflow.html
=> Remove olm.skipRanges from bundle CSV

docs/azure-openshift.md, docs/gcp-openshift.md
Docs for OCP 4.10 are finished, this PR aims at aligning with them.
=> Align docs with the official OCP ones

config/samples/infoblox/kustomization.yaml, config/samples/infoblox/operator_v1alpha1_infoblox_detailed.yaml, docs/infoblox-openshift.md, docs/scripts/cloud-formation-infoblox.yaml
Instructions similar to the other DNS providers like GCP and Azure.
Tested manually against [Infoblox NIOS DDI AWS product](https://aws.amazon.com/marketplace/pp/prodview-opxe3p2cgudwe).
=> docs: Manual test of Infoblox provider

docs/openshift.md
As per the feedback from https://issues.redhat.com/browse/CFE-322
=> doc: release-branch mapping

test/e2e/operator_test.go
Cluster ingress operator doesn't reconcile from any namespace anymore: [PR](https://github.com/openshift/cluster-ingress-operator/pull/740).
=> e2e: create ingress controller in openshift-ingress-operator namespace

pkg/operator/controller/credentials-secret/controller_test.go, pkg/operator/controller/credentials-secret/credentials_secret.go
[1] Adds check for specific keys in the secret for Azure, GCP, BlueCat and Infoblox providers
[2] Adds corresponding unit tests
=> Adds check for secret content

api/v1beta1/externaldns_webhook.go, api/v1beta1/webhook_test.go, test/e2e/util.go
CRD source is not implemented for the moment.
=> validating webhook: CRD source is not implemented

docs/infoblox-openshift.md
This PR adds more details about the configuration of the Infoblox after another exercise of this procedure (temporary licences expired).
=> docs: more details for infoblox configuration

README.md
This PR adds a README chapter to document the limitation on the length of the domain names managed by `ExternalDNS` instances.
=> OCPBUGS-91: document the domain name limitation

Dockerfile.bundle, Makefile, bundle/manifests/external-dns-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/external-dns-operator.clusterserviceversion.yaml, docs/openshift.md
Add a new OLM channel for the upcoming `1.2` release.
=> NE-1390: stable-v1.2 channel

OWNERS
Add @gcs278 as owner and remove inactive and old owners.
=> [release-1.0] OWNERS: add Grant, remove inactive and CFE

OWNERS
Andy and Miheer are not in NID team anymore. Greg, Ali and Ryan O'Hara joined NID team.
=> OWNERS: Network Edge team became Network Ingress&DNS

.tekton/external-dns-operator-bundle-container-ext-dns-optr-1-3-rhel-9-pull-request.yaml, Containerfile.external-dns-operator-bundle, Makefile, hack/README.md, hack/sync-version.sh
This pull request implements dynamic container image labels to improve traceability and align with Konflux best practices. The pipeline now uses the generate-labels task to automatically capture metadata like the commit ID and Git URL, which are then applied to the container image using the LABELS parameter in the build-container task. This ensures all built artifacts are correctly tagged with their source information.
=> NE-2076: Make container image labels dynamic
