openshift/external-dns-operator

Makefile
cmd/externaldns-operator/main.go
go.mod
pkg/operator/config/config.go
pkg/operator/controller/externaldns/controller.go
pkg/operator/operator.go
pkg/operator/scheme.go
vendor/modules.txt

**Makefile: Drop -mod=readonly from test directive**
Remove the `-mod=readonly` option from the unit test directive to ensure that we are using the `vendor` directory for unit tests.
**go.mod Add go-logr dependency**
go.mod:
Explicitly add go-logr in support of `operator.go`.
vendor/modules.txt:
Run `go mod vendor`.
**Break out operator configuration and startup**
controllers/externaldns_controller.go ->
pkg/operator/controller/externaldns/controller.go:
Move the exteraldns controller.go to a subdir of the new `controller` directory. Update the package name used for the controller.
pkg/operator/operator.go:
New file. Implements operator `New(...)` and `Start(...)` functions to move startup logic code out of `cmd/`.
pkg/operator/config/config.go:
New file to define options necessary to …

Break out operator configuration and startup

---

config/rbac/role.yaml
pkg/operator/controller/externaldns/controller.go
pkg/operator/controller/externaldns/namespace.go
pkg/operator/operator.go

This PR consists of the following commits:
**Move kubebuilder RBAC tags to operator.go**
pkg/operator/controller/externaldns/controller.go:
Remove kubebuilder RBAC tags.
pkg/operator/operator.go:
Move kubebuilder RBAC tags to all live in a single
location in operator.go. Add RBAC tags for namespace permissions.
config/rbac/role.yaml:
Run `make manifests`.
**externaldnscontroller: Implement New(...) function**
6a6a96f
pkg/operator/controller/externaldns/controller.go:
Implement a `New(...)` function for creating the externaldns
controller with customizations.
pkg/operator/operator.go:
Update externaldns controller creation calls.
Use a non-caching client, similair to that in the
ingress and DNS operators.
**externaldns: Add basic namespace reconciliation logic** …

Iterate on externaldnscontroller and add basic namespace reconciliation

---

Makefile
hack/verify-deps.sh
hack/verify-generated.sh
hack/verify-gofmt.sh

hack/verify-deps.sh:
Add script to verify `vendor/` when running on OpenShift CI.
hack/verify-gofmt.sh:
Add script to verify that all operator code is gofmt compliant.
hack/verify-generated.sh:
Add script to verify that generated manifests (e.g. the ExternalDNS CRD)
and deep copy functions are up to date.
Makefile:
Add new `verify` directive that calls the verify scripts in `hack/`.
/assign @alebedev87

Add verify command for OpenShift CI

---

go.mod
vendor/modules.txt

https://github.com/openshift/external-dns-operator/pull/9
imported a dependency without explicitly adding it to
go.mod or vendor. This commit fixes that.
---
This is a follow up to #13 and will save us a slight headache when we add the verify CI job.
/cc @alebedev87

go.mod: Explicitly add k8s API dep

---

README.md
config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml
config/default/manager_config_patch.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/rbac/auth_proxy_client_clusterrole.yaml
config/rbac/auth_proxy_role.yaml
config/rbac/auth_proxy_role_binding.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/externaldns_editor_role.yaml
config/rbac/externaldns_viewer_role.yaml
config/rbac/kustomization.yaml
config/rbac/role.yaml
config/rbac/role_binding.yaml
config/rbac/service_account.yaml

Preparation for OLM bundle as it has to include the deployment's spec and roles. As a positive side effect we can now use the manifests to deploy the operator on a cluster.
- Changed names for deployment, service account and other resources to better reflect the deliverable
- Updated deployment spec (resources, probes)
- Commented not used manifests (manager config, leader election)
```sh
$ oc apply -k config/default
namespace/external-dns-operator created
customresourcedefinition.apiextensions.k8s.io/externaldns.operator.openshift.io created
serviceaccount/external-dns-operator created
clusterrole.rbac.authorization.k8s.io/external-dns-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/external-dns-operator created
clusterrole.rbac.authorization.k8s.io/proxy-role …
```

Make deployable manifests

---

README.md
api/v1alpha1/externaldns_types.go
config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml
config/default/manager_auth_proxy_patch.yaml
config/default/manager_config_patch.yaml
config/manager/manager.yaml
config/rbac/role.yaml
config/samples/kustomization.yaml
config/samples/operator_v1alpha1_externaldns.yaml
go.mod
pkg/operator/config/config.go
pkg/operator/controller/externaldns/controller.go
pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/namespace.go
pkg/operator/controller/externaldns/service_account.go
pkg/operator/controller/names.go
pkg/operator/controller/names_test.go
pkg/operator/operator.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/modules.txt

Handover from https://github.com/openshift/external-dns-operator/pull/18.
Main differences from Steve's PR:
- Missing labelselector/labels added to deployment
- `ExternalDNS.Status` made optional
- Manifests updated to use `openshift-external-dns-operator` namespace
Tried on my local cluster:
```bash
$ oc logs deploy/external-dns-operator -c operator
2021-08-04T12:15:38.200Z	INFO	using operator namespace	{"namespace": "openshift-external-dns-operator"}
2021-08-04T12:15:38.200Z	INFO	using operand namespace	{"namespace": "external-dns"}
2021-08-04T12:15:38.200Z	INFO	using ExternalDNS image	{"image": "docker.io/bitnami/external-dns:latest"}
I0804 12:15:39.252345       1 request.go:668] Waited for 1.03609362s due to client-side throttling, not priority and fairness, request: …
```

Begin implementing deployment logic

---

Makefile

Currently docker is hard-coded as the container build tool. This change adds a make variable for the command name and also updates the make target names.

Added support for alternate container build tools

---

docs/usage.md

Added a usage.md file which contains instructions on how an `ExternalDNS` resource can be created which are configured with BlueCat and Infoblox DNS providers.

Added usage docs for Infoblox and BlueCat providers

---

Dockerfile.bundle
Dockerfile.openshift
Makefile
README.md
bundle/manifests/external-dns-operator-auth-proxy_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/external-dns-operator-auth-proxy_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/external-dns-operator-auth-proxy_v1_service.yaml
bundle/manifests/external-dns-operator_clusterserviceversion.yaml
bundle/manifests/external-dns-operator_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/external-dns-operator_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/external-dns-operator_v1_serviceaccount.yaml
bundle/manifests/externaldns.olm.openshift.io_crd.yaml
bundle/metadata/annotations.yaml

This PR adds `manifests/` and `metadata/` directories which contain the files to be present in OLM bundle for ExternalDNS Operator.
The PR adds some README instructions on how to install the bundle on the cluster. These instructions were tested manually:
```bash
$ oc -n openshift-marketplace get catalogsource external-dns-operator
NAME                    DISPLAY   TYPE   PUBLISHER   AGE
external-dns-operator             grpc               7m47s
$ oc -n openshift-marketplace get pods | grep external-dns-operator
external-dns-operator-jrkzc                                       1/1     Running     0          7m55s
$ oc -n external-dns-operator get csv,sub,pods
NAME                                                                      DISPLAY                VERSION   REPLACES   PHASE …
```

Add OLM bundle

---

.golangci.yaml
Makefile
hack/golangci-lint.sh
pkg/operator/controller/credentials-secret/controller.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/rbac_test.go
pkg/operator/controller/externaldns/service_account_test.go

[golangci-lint](https://golangci-lint.run) is a wrapper for multiple golang linters to detect common code issues.
This change adds a new make target which runs the linter and makes it a prerequisite for the `verify` target. Also added a configuration file for the linter.
Requires openshift/release#22506 to be merged first.

Added golangci-lint with only the default linters enabled

---

api/v1alpha1/externaldns_types.go
config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml

The `hostnameAnnotationPolicy` determines if any resources with the annotation is ignored or if DNS records should always be created for it. Since there is a default value `Ignore` this does not always have to be set.

Make hostnameAnnotationPolicy optional

---

Dockerfile.openshift

OLM operator shall not be a part of Release Payload as the release payload is composed of components that are critical to the core platform and cannot be installed through OLM (e.g. control plane and kubelet).
This commit removes this operator from release payload as it was causing olm /bundle/manifests to get copied in /manifests which CVO was consuming and causing failures as they were meant for OLM.

Bug: 2019001  OLM operators shall not be a part of realease payload.

---

docs/localdev.md

Added the step to generate certs in case of `webhook-server-cert` not found error

Update to create certs in event of cert failure

---

Makefile
bundle/manifests/external-dns-operator_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/externaldns.olm.openshift.io_crd.yaml

The command make index-image-build causes removes '---' in the yaml but leaves a blank line.
OLM parses this line a blank and then does not create the CRD which is present after this blank.
With this PR we remove blank lines from the yaml files.
This fix also adds the changed CRD after running command index-image-build which have the removed blank lines.

The command make index-image-build causes removes '---' in the yaml but leaves a blank line.

---

bundle/manifests/externaldns.olm.openshift.io_crd.yaml

This commit fixes the names plural field to singular name which is needed Match Type Exact.

This commit fixes the names plural field to singular name which is needed Match Type Exact.

---

README.md

Fixes step 2 b under Installing the `ExternalDNS` Operator using a custom index image on OperatorHub as it indicated step 0 which should be step 1.

Fixes step 2 b under Installing the `ExternalDNS` Operator using a custom index image on OperatorHub

---

bundle/metadata/annotations.yaml

`annotations.yaml` will be cloned by CPaaS midstream but the added annotations won't be customized by the CPaaS build.

Add OLM bundle and backport annotations

---

test/e2e/operator_test.go

Temporarily commenting out the tests so that the make target for e2e tests can be added to the CI configuration.

Disable e2e tests for CI

---

Makefile
README.md
bundle/manifests/external-dns-operator-auth-proxy_v1_service.yaml
bundle/manifests/external-dns-operator_clusterserviceversion.yaml
bundle/manifests/external-dns-operator_v1_serviceaccount.yaml

CVP bundle image linting errors/warnings:
```
time="2021-11-15T20:12:14Z" level=error msg="Error: Value external-dns-operator: invalid service account found in bundle. sa name cannot match service account defined for deployment spec in CSV"
time="2021-11-15T20:12:14Z" level=error msg="Error: Value error converting YAML to JSON: yaml: line 11: did not find expected ',' or '}': error decoding example CustomResource"
time="2021-11-15T20:12:14Z" level=error msg="Error: Value external-dns-operator-metrics-service: error validating object: metadata.namespace: Forbidden: not allowed on this type. &{map[apiVersion:v1 kind:Service metadata:map[labels:map[name:external-dns-operator] name:external-dns-operator-metrics-service namespace:external-dns-operator] spec:map[ports:[map[name:https port:8443 …
```

CPaaS: CVP bundle linting checks

---

bundle/manifests/external-dns-operator_clusterserviceversion.yaml
bundle/metadata/annotations.yaml

CVP CI deployment failed with the following error:
```
2021-11-17T08:48:07.125461845Z E1117 08:48:07.125439       1 queueinformer_operator.go:290] sync {"update" "oo-httfr/install-qzvtb"} failed: bundle unpacking failed: failed to turn bundle into steps: json: cannot unmarshal number into Go struct field ClusterServiceVersionSpec.spec.minKubeVersion of type string
```
Bundle metadata had a duplicate key for `channel.default`, it failed the rendering of the templates in the midstream.

CPaaS: CVP test fixes - minKubeVersion, duplicates in metadata

---

bundle/manifests/external-dns-operator_clusterserviceversion.yaml

XRef [OperatorSDK issue](https://github.com/operator-framework/operator-sdk/issues/5326) in case someone has the same problem.
Error I got from OLM:
```
2021-11-17T17:44:36.268071185Z I1117 17:44:36.268039       1 event.go:291] "Event occurred" object="oo-wcnfx/external-dns-operator" kind="Deployment" apiVersion="apps/v1" type="Normal" reason="ScalingReplicaSet" message="Scaled up replica set external-dns-operator-5f475c5c8b to 1"
2021-11-17T17:44:36.280741343Z I1117 17:44:36.280709       1 replica_set.go:588] Slow-start failure. Skipping creation of 1 pods, decrementing expectations for ReplicaSet oo-wcnfx/external-dns-operator-5f475c5c8b
2021-11-17T17:44:36.283388984Z I1117 17:44:36.283349       1 event.go:291] "Event occurred" object="oo-wcnfx/external-dns-operator-5f475c5c8b" …
```

CPaaS: CVP deployment check - service account must be referenced explicitly

---

Makefile
cmd/external-dns-operator/main.go
pkg/version/version.go
test/e2e/operator_test.go

Follow-up of https://github.com/openshift/external-dns-operator/pull/62. Aims at addressing the remarks about the conflicting hosted zone and go built-in resolver.

e2e test: use unique hosted zone and custom resolver

---

README.md
test/e2e/gcp.go
test/e2e/operator_test.go
test/e2e/util.go

Fix for https://github.com/openshift/external-dns-operator/pull/69.
Test run:
```
$ make test-e2e
go test \
-ldflags "-X github.com/openshift/external-dns-operator/pkg/version.SHORTCOMMIT=66ed8f7 -X github.com/openshift/external-dns-operator/pkg/version.COMMIT=66ed8f73b67cd0967dbb10e7a73e311f30888809" \
-timeout 1h \
-count 1 \
-v \
-tags e2e \
-run "" \
./test/e2e
I1125 00:30:45.556434   38386 request.go:665] Waited for 1.02962918s due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/operators.coreos.com/v1alpha1?timeout=32s
Ensuring hosted zone: 66ed8f7.example-test.info
=== RUN   TestOperatorAvailable
--- PASS: TestOperatorAvailable (0.02s)
=== RUN   TestExternalDNSRecordLifecycle
operator_test.go:171: Ensuring test namespace …
```

e2e: fix not working gcp helper

---

Makefile
test/e2e/operator_test.go

Add the possibility to skip e2e test for some cloud providers. This can be used later in case of known issues with some providers but most of the time it has to be left unused.
For now, we need it to be able to add CI jobs for GCP and Azure.
GCP e2e is already added but it's still failing so we need to disable it and add the CI job (what we should have done form the very beginning).

Skip gcp and azure e2e tests to add CI jobs

---

Makefile
README.md
api/v1alpha1/externaldns_webhook.go
api/v1alpha1/webhook_suite_test.go
api/v1alpha1/webhook_test.go
cmd/external-dns-operator/main.go
pkg/operator/config/config.go
pkg/operator/controller/credentials-secret/controller.go
pkg/operator/controller/credentials-secret/controller_test.go
pkg/operator/controller/credentials-secret/credentials_secret.go
pkg/operator/controller/externaldns/controller.go
pkg/operator/controller/externaldns/controller_test.go
pkg/operator/controller/externaldns/credentials-request.go
pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/pod.go
pkg/operator/operator.go
pkg/utils/utils.go
pkg/version/version.go
test/e2e/aws.go
test/e2e/azure.go
test/e2e/gcp.go

**Current situation**
The setup of the webhook checks for OpenShift API to set a global `api/v1alpha1` package variable which indicates whether it's openshift or not. In the same place the infrastructure config is retrieved and and another global variable for `PlatformStatus` is set in the same package. The rest of the code uses this to switchcase between pure Kubernetes and OpenShift installations.
_Problem 1_: platform detection and status have no logical adherence to the API wehbook. This is something which has to be done once but the webhook is not optimal place for this. 
_Problem 2_: testing with global variables is more difficult as the functions depend on external variants which are not easy to set and even more difficult to be reset to the previous values.
**Proposal**
Move the …

Avoid using global variables for configuration

---

bundle/manifests/external-dns-operator_clusterserviceversion.yaml

The operand image (external-dns) is now built in CPaaS. This change is to be able to pass the built image to the operator instead of the default (hard coded) one.

OLM bundle: add related operand image

---

Makefile
hack/golangci-lint.sh
test/e2e/aws.go
test/e2e/azure.go
test/e2e/gcp.go
test/e2e/operator_test.go
test/e2e/util.go

The e2e test files use build tags which prevent the linter from correctly detecting issues. This change runs the linter twice, one without any build tags and once with. Also fixed all issues detected.

Enable golangci-lint for e2e tests

---

Makefile
bundle/manifests/externaldns.olm.openshift.io_crd.yaml
hack/operator-sdk.sh
hack/verify-olm.sh

Add a new script to `make verify` target which:
- checks that the OLM bundle was updated with the latest files from `config/`
- runs `operator-sdk` bundle validation

Add the bundle generation check

---

test/e2e/operator_test.go
test/e2e/util.go

Instead of using two different libraries for DNS record lookups the test will use only miekg/dns library for both A and CNAME record lookups.

Use miekg dns library for A record lookups

---

api/v1alpha1/externaldns_types.go
bundle/manifests/externaldns.olm.openshift.io_crd.yaml
config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml

* `api/v1alpha1/externaldns_types.go` (`ExternalDNSInfobloxProviderOptions`): Change "kubebuilder:validation:Required" to "+kubebuilder:validation:Required".
* `bundle/manifests/externaldns.olm.openshift.io_crd.yaml`:
* `config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml`: Regenerate.
The `HostnameAnnotationPolicy` field is optional in some cases, and it has the `+optional` tag, so its kubebuilder tag should also indicate that the field is optional.
* `api/v1alpha1/externaldns_types.go` (`ExternalDNSSource`): Replace `+kubebuilder:validation:Required` with `+kubebuilder:validation:Optional`.
Add `+kubebuilder:validation:Optional` tags to all optional fields for consistency.
Before this change, some optional fields had both the `+optional` tag and the …

CRD fixes from #105 API review

---

README.md
bundle/manifests/external-dns-operator_clusterserviceversion.yaml
bundle/manifests/external-dns-operator_rbac.authorization.k8s.io_v1_role.yaml
cmd/external-dns-operator/main.go
config/rbac/extra-roles.yaml
config/rbac/operator_role.yaml
docs/proxy.md
pkg/operator/config/config.go
pkg/operator/controller/ca-configmap/ca_configmap.go
pkg/operator/controller/ca-configmap/controller.go
pkg/operator/controller/ca-configmap/controller_test.go
pkg/operator/controller/credentials-secret/controller.go
pkg/operator/controller/credentials-secret/controller_test.go
pkg/operator/controller/externaldns/controller.go
pkg/operator/controller/externaldns/controller_test.go
pkg/operator/controller/externaldns/credentials-request_test.go
pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/pod.go
pkg/operator/controller/externaldns/service_account_test.go
pkg/operator/controller/externaldns/status_test.go
pkg/operator/controller/names.go
pkg/operator/controller/utils/predicate.go
pkg/operator/controller/utils/predicate_test.go
pkg/operator/controller/utils/test/events.go
pkg/operator/controller/utils/test/vars.go
pkg/operator/operator.go

This PR allows the operator to inject trusted CA(s) into ExternalDNS (operand) containers.
**What's inside**
- New flag to pass the name of the configmap containing the CA (`cmd/external-dns-operator/main.go`)
- New controller to copy this configmap from the operator into the operand namespace (`pkg/operator/controller/ca-configmap/`)
- Updated desired ExternalDNS deployment. Mounts the trusted CA file now (`pkg/operator/controller/externaldns/pod.go`)
- Updated RBAC files (`configmaps` resources)
- New `pkg/operator/controller/utils` package for things used in all the controllers, mainly for `EventCollector` used in all the controllers' tests (`pkg/operator/controller/utils/`, `pkg/operator/controller/utils/test/`) 
- New doc for the proxy support (`docs/proxy.md`)

Bug 2041999: inject trusted CA to operand deployment

---

README.md

This PR aims at bringing smoother README experience. The idea is to be able to copy-paste without burden.
That's what I did for this:
- removed `$` from shell commands
- added the preparation of the environment to be able to automate the subsequent commands
- removed some manual steps
- grouped `make` commands
Also, added the contents links.

README: ease the command execution

---

README.md
api/v1alpha1/externaldns_types.go
bundle/manifests/external-dns-operator_clusterserviceversion.yaml
bundle/manifests/externaldns.olm.openshift.io_crd.yaml
config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml

Remove unused defaults in API and change the example from OLM bundle to make the default YAML in WebUI more meaningful.
**Note**: `YAML view` in Operator's WebUI is a merge of what's put into `ALM-example` of CSV manifest and the default values from CRD manifest. `ALM-example` takes precedence and if a certain YAML/JSON path (e.g. `.spec.source`) is set in the example the CRD defaults from this path are not used.

Bug 2049410: make meaningful default CR from Operator webUI

---

pkg/operator/controller/externaldns/credentials-request_test.go
pkg/operator/controller/names.go
tools/tools.go

To remove the usage of uninitialized `*testing.T` and to not log to `fmt`.

credentials request test: log encoding errors properly

---

pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/pod.go

Missing features after [the manual test of Infoblox provider](https://github.com/openshift/external-dns-operator/pull/123).

infoblox: TXT prefix and trusted CA support for non RHEL distributions

---

README.md
test/e2e/infoblox.go

Infoblox instance was moved to the ExternalDNS Operator's own account which got a public DNS domain.

e2e: infoblox - use public dns name

---

Dockerfile

Why this change?
- The base image from `Dockerfile` is used for the local builds only. CI and CPaaS (product release) use RHEL based go 1.17 images for the builds and runtime.
- `ubi8/go-toolset` is slow in its release cycle, `1.17` is still not in the latest image while `1.18` is already out for more than a month. It took them 8 month ([tags dates](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1), [1.16 releases](https://go.dev/doc/devel/release#go1.16)) to release the first `1.16` version, so I don't expect this to be any faster for `1.17`.

use public golang 1.17 for the local builds

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/rbac/extra-roles.yaml
config/rbac/operator_role.yaml
config/rbac/role.yaml
pkg/operator/operator.go

The operator doesn't create the operand's cluster role anymore, so it doesn't need the permissions required for the functioning operand.

rbac: remove operand cluster permissions

---

pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
test/e2e/operator_test.go

[1] Moves the secret checksum annotation from deployment's `metadata.annotations` to `spec.template.annotations`
[2] Adds an E2E to verify that at first DNS records are not created when wrong secret is supplied. When the wrong secret is updated with the right values, DNS records are created.

Adds annotation in podSpec to trigger re-creation of pods on secret credential update

---

README.md
bundle/manifests/external-dns-operator.clusterserviceversion.yaml
bundle/manifests/external-dns_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
config/manager/manager.yaml
config/manifests/bases/external-dns-operator.clusterserviceversion.yaml
config/rbac/operand_rolebinding.yaml
docs/design/separate-operand-namespace.md
docs/migration-guides.md
test/e2e/operator_test.go

Operand can be deployed in the operator namespace:
```
$ oc -n external-dns-operator get pods
NAME                                     READY   STATUS    RESTARTS   AGE
external-dns-operator-6644944b64-2txst   2/2     Running   0          2m12s
$ oc get ns external-dns
Error from server (NotFound): namespaces "external-dns" not found
$ oc apply -f infoblox-cr.yaml 
externaldns.externaldns.olm.openshift.io/sample-infoblox created
$ oc -n external-dns-operator get pods
NAME                                            READY   STATUS    RESTARTS   AGE
external-dns-operator-6644944b64-2txst          2/2     Running   0          3m40s
external-dns-sample-infoblox-57f97c7849-q2rp9   1/1     Running   0          59s
$ oc get externaldns 
NAME              AGE
sample-infoblox   68s
$ oc -n …
```

Deploy operands in the operator's namespace

---

pkg/operator/controller/externaldns/controller.go
pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/utils/test/vars.go

Handle the rotation of the trusted CA using an annotation on the deployment with the configmap's checksum.

trusted CA: add checksum annotation to deployment

---

Makefile
README.md
bundle/manifests/external-dns-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
bundle/manifests/external-dns-operator-metrics-service_v1_service.yaml
bundle/manifests/external-dns-operator.clusterserviceversion.yaml
bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
bundle/manifests/prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
config/default/kustomization.yaml
config/default/manager_insecure_tls_auth_proxy_patch.yaml
config/prometheus/insecure_tls_patch.yaml
config/prometheus/kustomization.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/kustomization.yaml
config/rbac/prometheus_role.yaml
config/rbac/prometheus_role_binding.yaml

Enable prometheus metrics scraping

---

api/v1beta1/externaldns_webhook.go
main.go
pkg/operator/config/config.go
pkg/operator/controller/externaldns/controller.go
pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/status.go
pkg/operator/controller/externaldns/status_test.go
pkg/operator/operator.go

- `RequeueAfter` the configurable period if the credentials secret or the trusted CA configmap not found. This helps to greatly reduce the number of repeating error logs.
- `CredentialsSecretExists` status condition is added to signal a missing secret.
- Bonus: bug in the platform detection - error if the check for the `operator.openshift.io` API group fails

Add postponed requeuing and credentials exist status condition

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Upstream fixes:
- https://github.com/kubernetes-sigs/external-dns/pull/2811
- https://github.com/kubernetes-sigs/external-dns/pull/2913

Update the operand image to catch up on 2 upstream fixes

---

pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/pod.go

Since the addition of the new format of TXT records in external-dns `0.12.0` the TXT records are prepended with the type of the DNS record which doesn't comply with the standards of Azure DNS in case of the wildcards: the wildcard symbol (`*`) has to be the leftmost one.
Related issue: https://github.com/kubernetes-sigs/external-dns/issues/2922

OCPBUGS-819: Azure provider - add wildcard replacement for TXT records

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/manager/manager.yaml
pkg/operator/config/config.go

The operand image built in [openshift/external-dns](https://github.com/openshift/external-dns) repository is now mirrored to the dedicated quay.io organization. This breaks the dependency on the openshift quay.io organization therefore unlocking the potential for a different life cycle.

CFE-611: use dedicated quay.io organization for operand image

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/manager/manager.yaml

Integrate the rebase to `0.13.1`: https://github.com/openshift/external-dns/pull/46.

CFE-612: Update the operand image to 0.13.1

---

pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/operator.go

Some lessons learnt from the other operators:
- `defaultMode` for volumes is not part of the expected specification however it's added by the defaulting mechanism which leads to the fight between the operator and API server
- accept unsolicited containers to enable use cases like side car container injection (service mesh or others)
- `Operator` type: unused fields removed

OCPBUGS-2793: deployment: ignore defaultmode for volumes, accept unsolicited containers

---

Dockerfile.bundle
Makefile
README.md
bundle/manifests/external-dns-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manifests/bases/external-dns-operator.clusterserviceversion.yaml
docs/proxy.md

This PR adds the new channels:
- `stable-v1.1` for the upcoming release
- `stable-v1` for the users ready to streamline the minor version upgrades
`stable-v1` channel would allow the engineering to reduce the configuration burden too as the channel needs to be mentioned in all the docs and the Prow CI configuration.
`stable-v1.0` is kept in `main` for the moment to not break CI as it uses `stable-v1.0` channel to install the operator. A follow-up PR will need to be done to remove it.

CFE-615: release 1.1: add stable-v1.1 and stable-v1 channels

---

pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go

[Previous PR](https://github.com/openshift/external-dns-operator/pull/176) for the same ticket introduced a new bug: unsolicited containers from the previous states of ExternalDNS CR are kept. The bug was caught by @lihongan and has [this visible consequence](https://issues.redhat.com/browse/OCPBUGS-2793?focusedCommentId=21361960&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21361960) when the zone ID (`ExternalDNS.spec.zones`) of an existing instance of ExternalDNS is changed.
**Bad case scenario**:
- ExternalDNS CR has 1 zone ID specified: `x.y.z`
- Operator already spawned a deployment for this instance. This deployment has one single container named `external-dns-<hash-for-zone-x-y-z>` (note that for each zone ID specified the operator creates a …

OCPBUGS-2793: deployment - remove unsolicited containers

---

hack/golangci-lint.sh
pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go

As per the upstream update: https://github.com/kubernetes-sigs/external-dns/pull/2772. ExternalDNS is currently unable of handling multiple parallel instances (no leader election implemented). This may result into split brain situation during the rolling upgrades.

OCPBUGS-3630: deployment: enforce recreate strategy to avoid conflicts during upgrades

---

api/v1beta1/externaldns_types.go
bundle/manifests/externaldns.olm.openshift.io_externaldnses.yaml
config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml
docs/usage.md

By adding a default value to the `spec.provider.aws.credentials` field, it enables the configuration of `spec.provider.aws.assumeRole` for an OpenShift user that doesn't need to explicitly specify the `credentials` field. Otherwise, an OpenShift user must manually insert `""` as the credentials name to use the `assumeRole` field.
This improves user experience for the current v1beta1 release of ExternalDNS Operator while not introducing any breaking changes to the API. We are planning to properly fix this issue in a future ExternalDNS Operator API version by converting `Credentials` to an optional pointer.
Epic: https://issues.redhat.com/browse/NE-1299

NE-1323: Add default to AWS credentials field

---

OWNERS

This PR adds @gcs278  as owner and removes old owners from the CFE team.

OWNERS: add Grant, remove CFE

---

OWNERS

This PR adds @gcs278 as owner and removes old owners from the CFE team.

[release-1.1] OWNERS: add Grant, remove CFE

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/manifests/bases/external-dns-operator.clusterserviceversion.yaml

According to the Red Hat Operator's [Best practices](https://docs.engineering.redhat.com/display/CFC/Best_Practices) the infrastructure annotations are now required. The [old "infrastructure-features" annotation is deprecated](https://github.com/openshift/openshift-docs/pull/69579) hence it's removed. The old list of features is mapped to the new set.

OCPBUGS-26538: add infrastructure annotations

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml

This PR sets the termination message policy to [`FallbackToLogsOnError`](https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure/#customizing-the-termination-message) on all the operator containers.

OCPBUGS-28230: Add FallbackToLogsOnError to all pod containers

---

assets/README.md
assets/iam_policy.json
docs/usage.md
pkg/operator/controller/externaldns/deployment.go
pkg/operator/controller/externaldns/deployment_test.go
pkg/operator/controller/externaldns/pod.go

- [Add bound service account token to operand deployment](https://github.com/openshift/external-dns-operator/commit/140a78bb49947d9100d1e8976767ee569495f7a4)
- [Update docs with STS chapter](https://github.com/openshift/external-dns-operator/commit/daaf9f67f83c9fc6833cad7878fe72b93cbd92f0)
- [Relax node placement for operand](https://github.com/openshift/external-dns-operator/commit/a5dfddb958ef7624b7eba8e20daedfab57ecfa7e)

OCPBUGS-37059: Support deployment on HCP clusters

---

docs/usage.md

I used the dumb `Ctrl+V` + `>` Vim shift to align the code blocks with the lists. This broke the YAML indent. This PR restores the right YAML indent.

OCPBUGS-37059: docs/usage.md - fix broken yaml indent

---

docs/infoblox-openshift.md
docs/scripts/cloud-formation-infoblox.yaml

- Enhanced "Provision Infoblox on AWS" documentation with more details about
configuration and license setup.
- Updated example cloud formation script with the new Infoblox AMI version (8.6.z),
as the previous version (8.5.z) is now end-of-support.

OCPBUGS-37308: Update Infoblox documentation

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/manager/manager.yaml

This PR updates the operand image to include the latest changes from the upstream's 0.14.2 version, as introduced in [the rebase PR](https://github.com/openshift/external-dns/pull/58).
External-dns repository from quay.io: [link](https://quay.io/repository/external-dns-operator/external-dns?tab=tags) (`latest` tag).

NE-1802: Update the operand image to 0.14.2

---

.ci-operator.yaml
Dockerfile

Change RHEL version to RHEL9 for building and base images. [The operand image with RHEL9](https://github.com/openshift/external-dns/pull/61) has already been added as a part of https://github.com/openshift/external-dns-operator/pull/225.

OCPBUGS-41683: Use RHEL9 as baseimage and build root image

---

Makefile
api/v1beta1/externaldns_types.go
bundle/manifests/externaldns.olm.openshift.io_externaldnses.yaml
catalog/external-dns-operator/bundle.yaml
config/crd/bases/externaldns.olm.openshift.io_externaldnses.yaml

- Removed links that don't add value and may mislead users (AWS, Infoblox: secret format).
- Pinned remaining links to specific commits and anchored them to relevant chapters.

OCPBUGS-36797: Revisit links to upstream docs in API

---

Dockerfile.bundle
Makefile
bundle/manifests/external-dns-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
catalog/external-dns-operator/bundle.yaml
catalog/external-dns-operator/channel.yaml
config/manifests/bases/external-dns-operator.clusterserviceversion.yaml
docs/openshift.md
test/e2e/infoblox.go

This PR:
- updates `config/manifests`  to use the new version (`1.3.0`) for CSV
- regenerates the bundle using `make bundle` command
- updates `catalog` with new bundle version and new minor version channel using `make catalog` command
- updates the bundle metadata in `Dockerfile.bundle` and `bundle/metadata/annotations.yaml` with the new minor version channel
- updates `docs/openshift.md` with the new (and missing) branch mappings
Also:
- New commit added to handle the flaky patching of operator subscription with Infoblox CA.
- Another new commit added to fix the CPaaS CVP warning about missing valid subscription annotation.

NE-1777: Add new OLM channel for 1.3 release

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/samples/infoblox/operator_v1alpha1_infoblox_detailed.yaml
config/samples/infoblox/operator_v1alpha1_infoblox_openshift.yaml
config/samples/infoblox/operator_v1beta1_infoblox_openshift.yaml
docs/infoblox-openshift.md
pkg/operator/controller/externaldns/deployment_test.go
test/e2e/infoblox.go

This PR aims at updating the nominal version of Infoblox's WAPI we test our operator against. The test Infoblox instance we use is recommended to be used with `2.12.2` WAPI version ([Infoblox ref](https://community.infoblox.com/cixhp49439/attachments/cixhp49439/IPAM/6153/2/NIOS_8.6.2_ReleaseNotesREVC.pdf)).

OCPBUGS-42220: Infoblox - use 2.12.2 WAPI version

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/samples/azure/kustomization.yaml
config/samples/azure/operator_v1beta1_externaldns_openshift_private.yaml
docs/azure-openshift.md

- Adds an example of the usage of the private dns zone for the Azure provider
- Addresses https://github.com/openshift/external-dns-operator/issues/197

OCPBUGS-32058: docs - add example of private dns zone for Azure provider

---

bundle/manifests/external-dns-operator.clusterserviceversion.yaml
config/manager/manager.yaml

This commit changes the strategy used to reference the operand image in the operator's deployment manifest. The `latest` floating tag is now used to avoid issues with older mirrored images being removed.
Since these manifests are used only in CI presubmits, there is no risk of breaking future releases, which will have pinned versions (SHA256 digests) for all images.
Similar PR in ALBO: https://github.com/openshift/aws-load-balancer-operator/pull/161.

OCPBUGS-57339: Use floating tag for operand image

---

renovate.json

Add Renovate/MintMaker configuration which:
- Configures base and builder images updates restricted to be only within the major version 9.
- go-toolset version updates restricted to be within the minor version 1.22.
- Disable all gomod bump PRs to avoid the unnecessary noise. The automated updates were found to be failing the build too often to be considered useful.
- Konflux dependencies updates (tekton pipelines) configuration. This was based on the default MintMaker configuration [konflux-ci/mintmaker/config/renovate/renovate.json](https://github.com/konflux-ci/mintmaker/blob/5f632ab7a9aabdff16092cc05127995c37c81d94/config/renovate/renovate.json#L70-L116):
One difference is that updates to quay.io/konflux-ci/konflux-vanguard were also added to be grouped into a single PR. The source …

NE-2073: Configure Renovate updates of images and tekton pipelines

---

catalog/external-dns-operator/bundle.yaml
catalog/external-dns-operator/channel.yaml

Updated the bundle image with contents from commit 75de5293cbf436b4971384664e4982e136f93b41 and regenerated the catalog using `make catalog`.
Steps performed:
- Built and pushed the bundle image:
- `podman build -t quay.io/external-dns-operator/external-dns-operator-bundle:latest -f Dockerfile.bundle .`
- `podman push quay.io/external-dns-operator/external-dns-operator-bundle:latest`
- Generated FBC with `make catalog`.
Continuation of https://github.com/openshift/external-dns-operator/pull/275. This PR updates the FBC contents from the latest bundle.

NE-2076: Update catalog to version 1.3.1
